version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: secure_root_password123
      MYSQL_DATABASE: bank
      MYSQL_USER: akshit
      MYSQL_PASSWORD: my_password123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
    driver: local
